import { makeStyles } from "@material-ui/core/styles";

export default makeStyles((theme) => ({
  media: {
    height: 0,
    paddingTop: "calc(100% * 3 / 4)",
  },
  imageSvg: {
    position: "absolute",
    width: "125px",
    height: "60px",
    bottom: "144px",
    left: "0px",
  },
  avatar: {
    position: "absolute",
    width: "40px",
    height: "40px",
    zIndex: "9",
    bottom: "151px",
    left: "42px",
    cursor: "pointer",
  },
  box: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    alignItems: "flex-start",
  },
  card: {
    borderRadius: "10px",
    position: "relative",
    [theme.breakpoints.down("xs")]: {
      marginLeft: "25px",
      width: "85%",
    },
  },
  cardContent: {
    display: "flex",
    flexDirection: "column",
    position: "relative",
    marginTop: "20px",
    height: "150px",
  },
  overlay: {
    position: "absolute",
    top: "20px",
    left: "30px",
    color: "white",
  },
  overlay2: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    width: "40px",
    height: "40px",
    top: "-50px",
    right: "20px",
    backgroundColor: "#fff8e1",
    borderRadius: "50%",
    zIndex: "50",
    transition: theme.transitions.create(["top", "background-color"], {
      duration: theme.transitions.duration.standard,
      easing: theme.transitions.easing.easeInOut,
    }),
    "&:hover": {
      backgroundColor: "#ffd54f",
    },
    "&.menuActive $dropdown": {
      opacity: 1,
      transform: "translateY(0)",
      pointerEvents: "auto",
    },
  },
  dropdown: {
    position: "absolute",
    bottom: -102,
    right: 0,
    listStyle: "none",
    width: "135px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    borderRadius: "15px",
    transform: "translateY(-5px)",
    transition: "all 0.4s ease",
    backgroundColor: "#f7f1f0",
    opacity: 0,
    pointerEvents: "none",
  },
  menuItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    margin: "5px 6px",
    padding: "8px",
    borderRadius: "15px",
    "&:hover": {
      backgroundColor: theme.color.buttonHover,
    },
  },
  BookIcon: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    width: "40px",
    height: "40px",
    top: "-50px",
    left: "20px",
    backgroundColor: "#fff8e1",
    borderRadius: "50%",
    zIndex: "50",
    transition: theme.transitions.create(["top", "background-color"], {
      duration: theme.transitions.duration.standard,
      easing: theme.transitions.easing.easeInOut,
    }),
    "&:hover": {
      backgroundColor: "#ffd54f",
    },
  },
  title: {
    fontFamily: "inherit",
    padding: "4px 26px",
    cursor: "pointer",
    "&:hover": {
      textDecoration: "underline",
    },
  },
  cardActions: {
    display: "flex",
    justifyContent: "space-between",
    marginTop: "auto",
    width: "100%",
  },
  imageAction: {
    position: "absolute",
    width: "100%",
    top: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.7)",
    backdropFilter: "blur(2px)",
    opacity: 0,
    transition: theme.transitions.create("opacity", {
      duration: theme.transitions.duration.standard,
      easing: theme.transitions.easing.easeInOut,
    }),
  },
  cardActionArea: {
    position: "relative",
    cursor: "pointer",
    "&:hover  $overlay2, &:hover $BookIcon": {
      top: "17px",
    },
    "&:hover $imageAction": {
      opacity: 1,
    },
  },
  commentsSection: {
    display: "flex",
    alignItems: "center",
    color: "gray",
  },
  deleteBox: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: "1000",
    backgroundColor: "rgba(255,255,255,0.6)",
  },
}));
